#!/bin/bash
set -e

# ==========================================
# TLS Certificates
# ==========================================

mkdir -p /etc/kubernetes/tls
tar -C /etc/kubernetes/tls -xf /tmp/tls.tar


# ==========================================
# Files
# ==========================================

TARGET_DIR=/etc/systemd/system/
if [ ! -e $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi
cp /tmp/files/systemd/kubelet.service $TARGET_DIR
cp /tmp/files/systemd/kube-apiserver.service $TARGET_DIR
cp /tmp/files/systemd/kube-controller-manager.service $TARGET_DIR
cp /tmp/files/systemd/kube-scheduler.service $TARGET_DIR
cp /tmp/files/systemd/kube-proxy.service $TARGET_DIR

TARGET_DIR=/etc/systemd/system/docker.service.d
if [ ! -e $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi
cp /tmp/files/systemd/docker.service.d/10-dev.conf $TARGET_DIR
cp /tmp/files/systemd/docker.service.d/40-flannel.conf $TARGET_DIR

TARGET_DIR=/etc/systemd/system/flanneld.service.d
if [ ! -e $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi
cp /tmp/files/systemd/flanneld.service.d/40-ExecStartPre-symlink.conf $TARGET_DIR

TARGET_DIR=/etc/flannel
if [ ! -e $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi
cp /tmp/files/flannel/options.env $TARGET_DIR


# ==========================================
# Systemd services
# ==========================================

systemctl enable etcd2
systemctl start etcd2

sh /tmp/files/scripts/init-flannel.sh

systemctl daemon-reload

systemctl enable kubelet
systemctl start kubelet

systemctl enable kube-apiserver
systemctl start kube-apiserver

systemctl enable kube-controller-manager
systemctl start kube-controller-manager

systemctl enable kube-scheduler
systemctl start kube-scheduler

systemctl enable kube-proxy
systemctl start kube-proxy

sh /tmp/files/scripts/init-kube-system.sh

systemctl stop update-engine
systemctl mask update-engine

